### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Tanjirouzumaki** [PixelatedW/mineminenomi#206] opened 2021-01-20 23:43 UTC
Hey anyone have any issues with quests? I found a dojo and accepted a quest but now every time I right click any person from a dojo again the game crashes.
let me know

**Comment by FGpisces** [comment] 2021-01-21 00:32
Please include the crash log to report a crash so we can see where the problem is.

**Comment by FGpisces** [comment] 2021-02-04 22:35
Closing issue, provide the crashlog when reporting an issue.

**Closed by FGpisces** 2021-02-04 22:35 UTC
